const actionTypes = {
  CREATE_TASK_BEGIN:   'CREATE_TASK_BEGIN',
  CREATE_TASK_ERROR:   'CREATE_TASK_ERROR',
  CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
  FETCH_TASKS_BEGIN:   'FETCH_TASKS_BEGIN',
  FETCH_TASKS_ERROR:   'FETCH_TASKS_ERROR',
  FETCH_TASKS_SUCCESS: 'FETCH_TASKS_SUCCESS'
};

export default actionTypes;
